const { randomize } = require("./utils.js")

const createRiver = () => {
    const rivers = Math.floor(Math.random() * 3) + 1
    return rivers
}
// returns a number between 1 and 3, to determine how many river segments will be part of the journey

const createMountains = () => {
    const mountains = Math.floor(Math.random() * 2) + 1
    return mountains
}

const createForests = () => {
    const forests = Math.floor(Math.random() * 2) + 1
    return forests
}

const createPlains = () => {
    const plains = Math.floor(Math.random() * 4) + 1
    return plains
}

// In the **journey** module, there is a `journeyMaker()` function. In that function, there is a variable named `areas` which will have the value of an object. Use your debugger to show what the value of each key is on that object.

const journeyMaker = () => {
    const journey = []

    // the areas object is created to hold random values for each type of terrain.  these are keys, each corresponding to one type of terrain and the values are the random numbers generated by the crate function 
    const areas = {
        rivers: createRiver(),
        forests: createForests(),
        mountains: createMountains(),
        plains: createPlains()
    }

//     Also in the **journey** module, there is the following code:
 
//    ```js
//    for (let forestNumber = 0; forestNumber < areas.forests; forestNumber++) {
//       journey.push("forest")
//    }
//    ```
//    Explain this code with your best vocabulary.


    for (let riverNumber = 0; riverNumber < areas.rivers; riverNumber++) {
        journey.push("river")
    }


    for (let forestNumber = 0; forestNumber < areas.forests; forestNumber++) {
        journey.push("forest")
    }
    // adds the string "forest" to the journey array, repeating it based on the number of forests generated in the areas.forest value. this loop runs as many times as the number of forest (a random number between 1 and 2, generated by createForests ()----)

    for (let mountainNumber = 0; mountainNumber < areas.mountain; mountainNumber++) {
        journey.push("mountain")
    }

    for (let plainNumber = 0; plainNumber < areas.plains; plainNumber++) {
        journey.push("plain")
    }

    return randomize(journey)
}

// returns a randomized array of 

module.exports = {
    createRiver, createForests,
    createMountains, createPlains, journeyMaker
}